name: Coverage

on:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm t -- --coverage
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          fail_ci_if_error: true
          files: ./clover.xml
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true